#! /usr/bin/env tclsh

# Search and replace (using regsub)

set SEARCHTERM [lindex $argv 0]
set REPLACEMENT [lindex $argv 1]

if {[info exists env(s)]} {
	puts [regsub -all -lineanchor -- $SEARCHTERM $env(s) $REPLACEMENT]
} elseif {[info exists env(f)]} {
	set f [open $env(f)]
	set txt [read $f]
	close $f
	
	set txt [regsub -all -lineanchor -- $SEARCHTERM $env(s) $REPLACEMENT]
	file copy $env(f) $env(f).old
	
	set f [open $env(f) w]
	puts $f $txt
	close $f
}
